## Pandas: część 3

In [1]:
import pandas as pd # importowanie biblioteki Pandas

### Łączenie ramek danych za pomocą metod `merge` i `concat`

In [3]:
df1 = pd.read_csv('IHME-GBD_2019_DATA-15798851-2/IHME-GBD_2019_DATA-15798851-2.csv')

# załaduj drugi plik zapisany na komputerze
# link do pobrania https://drive.google.com/file/d/1uK1edpdqVFJnFaGTWGpVOlaJHgoCBwli/view?usp=sharing 
# źródło danych Global Burden of Disease Study 2019 (GBD 2019) Results.
# Seattle, United States: Institute for Health Metrics and Evaluation (IHME), 2020.
# Strona http://ghdx.healthdata.org/gbd-results-tool
# DALYs (Disability-Adjusted Life Years) — ten wskaźnik oznacza
# ile lat zdrowego i produktywnego życia tracą ludzie z powodu niepełnosprawności i przedwczesnej śmierci z powodu różnych chorób
df1.head(10) # wyświetlamy pierwszy 10 wierszy

,measure,location,sex,age,cause,metric,year,val,upper,lower
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Number,2012,1659.038707,2126.829521,1239.172699
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Number,2012,874.432466,1186.560596,618.271780
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Number,2012,2533.471173,3231.220866,1868.204609
5,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Percent,2012,0.003799,0.004849,0.002863
6,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Percent,2012,0.002202,0.002889,0.001585
7,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Percent,2012,0.003038,0.003885,0.002298
8,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784
9,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204

In [5]:
df2 = pd.read_csv("IHME-GBD_2019_DATA-ff08d9bc-1/IHME-GBD_2019_DATA-ff08d9bc-1.csv")

# załaduj pierwszy plik zapisany na komputerze
# link do pobrania https://drive.google.com/file/d/16fM_JEC5GAkYEDaDgzROrBm8loi9RZRZ/view
# źródło danych Global Burden of Disease Study 2019 (GBD 2019) Results, сайт http://ghdx.healthdata.org/gbd-results-tool
# w pliku dane o zgonach osób z różnych przyczyn dla 204 krajów w latach 2000-2019

df2.head(10)

,measure,location,sex,age,cause,metric,year,val,upper,lower
0,Deaths,Samoa,Male,All Ages,Chronic respiratory diseases,Rate,2000,64.470214,81.808307,53.476793
1,Deaths,Samoa,Female,All Ages,Chronic respiratory diseases,Rate,2000,55.234399,77.883497,39.978647
2,Deaths,Samoa,Both,All Ages,Chronic respiratory diseases,Rate,2000,60.039961,76.013089,49.941986
3,Deaths,Samoa,Male,All Ages,Skin and subcutaneous diseases,Rate,2000,2.246741,3.467454,1.438979
4,Deaths,Samoa,Female,All Ages,Skin and subcutaneous diseases,Rate,2000,1.368385,1.945448,0.866099
5,Deaths,Samoa,Both,All Ages,Skin and subcutaneous diseases,Rate,2000,1.825409,2.569260,1.259226
6,Deaths,Samoa,Male,All Ages,Transport injuries,Rate,2000,25.920294,36.084587,18.130636
7,Deaths,Samoa,Female,All Ages,Transport injuries,Rate,2000,10.099048,13.447738,7.330908
8,Deaths,Samoa,Both,All Ages,Transport injuries,Rate,2000,18.331128,25.000813,13.148053
9,Deaths,Samoa,Male,All Ages,Unintentional injuries,Rate,2000,28.989384,39.579940,20.833239

In [6]:
df1.rename(columns = {'val': 'daly_val', 'upper':'daly_upper', 'lower':'daly_lower'}, inplace = True)
df2.rename(columns = {'val': 'deaths_val', 'upper': 'deaths_upper', 'lower':'deaths_lower'}, inplace = True)
# zmień nazwy kolumn zgodnie ze wskaźnikami: liczba utraconych lat produkcyjnych dla 1 ramki danych (DALY)
# i śmiertelność dla drugiej ramki danych ()

In [7]:
df_all = pd.merge(df1, df2, on = ['location', 'sex', 'age', 'cause', 'metric', 'year'], how = 'inner') 

# inner: weź tylko dopasowania z dwóch ramek danych
# określiliśmy nazwy kolumn, według których łączymy dataframe'y, ale można też łączyć według indeksu -
# liczba porządkowa, która jest pozostawiona pionowo z [df1.index] bez cudzysłowów

In [8]:
# pd.merge (df1, df2, on = ['nazwa kolumny'], how = 'inner') # bierze tylko wiersze, które pasują do obu ramek danych
# pd.merge (df1, df2, on = ['nazwa kolumny'], how = 'outer') # wszystkie wiersze ze wszystkich ramek danych, nie ma znaczenia, czy pasują, czy nie
# pd.merge (df1, df2, on = ['nazwa kolumny'], how = 'left') # tylko pasujące wiersze + wszystkie wiersze z lewej ramki danych
# pd.merge (df1, df2, on = ['nazwa kolumny'], how = 'right') tylko pasujące wiersze + wszystkie wiersze z prawej ramki danych

In [9]:
df_all.head()

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594

In [10]:
df_all.shape # ile wierszy i kolumn znajduje się w ramce danych

(97976, 14)

In [11]:
 # podziel ramkę danych na dwie ramki danych: pierwsza z wierszami od pierwszego do 50 000, druga od 50 000 do ostatniego
df_all_1 = df_all.iloc[:50000,:]
df_all_2 = df_all.iloc[50000:,:]

In [12]:
df_all_new = pd.concat([df_all_1, df_all_2], axis = 0) # połącz ramki danych: jeśli axis = 0, to po wierszach, jeśli
# axis = 1, potem według kolumn
df_all_new.shape # nowa dataframe ma taką samą liczbę wierszy i kolumn jak przed podziałem

(97976, 14)

### 2. Dodawanie nowych kolumn za pomocą operacji matematycznych

In [13]:
# dodaj nową kolumnę, która będzie miała zaokrągloną wartość z innej kolumny
df_all["deaths_val_round"] = df_all["deaths_val"].round(decimals = 1)

In [14]:
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2

In [15]:
# dodać nową kolumnę sumując wartości kilku innych
df_all["deaths_total"] = df_all["deaths_val"] + df_all["deaths_upper"] + df_all["deaths_lower"]
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896

In [16]:
# dodać nową kolumnę sumując wartości kilku innych metodą loc
# oprócz sumy można odczytać mean (średnią), median (medianę), max, min, std (odchylenie standardowe) itp.
df_all["total_loc"] = df_all.loc[:, "deaths_val":"deaths_lower"].sum(axis = 1)
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total,total_loc
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896,49.675896

In [17]:
# dodaj nową kolumnę sumując wartości kilku innych metodą iloc
# co ważne, przy korzystaniu z metody iloc nie jest uwzględniana właściwa wartość (numer kolumny), więc jeśli potrzebujemy kolumn z liczbami
# 11, 12 i 13, musisz podać od 11 do 14: df_all.iloc [:, 11:14] 

df_all["total_iloc"] = df_all.iloc[:, 11:14].sum(axis = 1)

In [18]:
df_all

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,deaths_val_round,deaths_total,total_loc,total_iloc
0,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Maternal and neonatal disorders,Rate,2012,7475.212700,9104.773541,6157.428603,Deaths,89.867238,110.176286,74.001324,89.9,274.044849,274.044849,274.044849
1,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Maternal and neonatal disorders,Rate,2012,7814.344518,9667.960848,6289.146375,Deaths,89.365457,111.497307,71.539316,89.4,272.402080,272.402080,272.402080
2,DALYs (Disability-Adjusted Life Years),Gambia,Male,All Ages,Substance use disorders,Rate,2012,179.493660,230.104586,134.067784,Deaths,1.101136,1.545407,0.786638,1.1,3.433182,3.433182,3.433182
3,DALYs (Disability-Adjusted Life Years),Gambia,Female,All Ages,Substance use disorders,Rate,2012,91.400543,124.025911,64.625204,Deaths,0.227136,0.296917,0.173921,0.2,0.697975,0.697975,0.697975
4,DALYs (Disability-Adjusted Life Years),Gambia,Both,All Ages,Substance use disorders,Rate,2012,134.688036,171.782808,99.320179,Deaths,0.656605,0.896138,0.490594,0.7,2.043338,2.043338,2.043338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97971,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Chronic respiratory diseases,Rate,2019,602.342558,732.856075,491.019574,Deaths,10.783192,13.484120,8.267941,10.8,32.535253,32.535253,32.535253
97972,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Chronic respiratory diseases,Rate,2019,635.274862,755.292643,530.146531,Deaths,13.025678,15.412885,10.664151,13.0,39.102714,39.102714,39.102714
97973,DALYs (Disability-Adjusted Life Years),Malawi,Male,All Ages,Unintentional injuries,Rate,2019,1318.844977,1717.917036,1037.489279,Deaths,20.824550,27.026330,16.310791,20.8,64.161670,64.161670,64.161670
97974,DALYs (Disability-Adjusted Life Years),Malawi,Female,All Ages,Unintentional injuries,Rate,2019,813.052440,1042.011143,638.605025,Deaths,11.865525,15.430914,9.199714,11.9,36.496153,36.496153,36.496153
97975,DALYs (Disability-Adjusted Life Years),Malawi,Both,All Ages,Unintentional injuries,Rate,2019,1059.021476,1334.453539,846.543870,Deaths,16.222336,20.617369,12.836190,16.2,49.675896,49.675896,49.675896

In [19]:
# usuń niepotrzebne kolumny, aby nie przeszkadzać
df_all.drop(['deaths_val_round','deaths_total', 'total_loc','total_iloc'], axis = 1, inplace = True)

### 3. Dodawanie nowych kolumn z pomocą funkcji lambda

In [20]:
# tworzymy listę krajów
CIS_2020 = ['Poland', 'Hungary', 'Italia', 'Germany', 'France', 
            'Spain', 'Romania']

In [22]:
# za pomocą funkcji lambda określamy, że jeśli kraj („location”) jest zawarty w liście, to nowa kolumna będzie miała postać „CIS_2020”
# będzie true, jeśli nie, to false
df_all['CIS_2020'] = df_all['location'].apply(lambda x: True if x in CIS_2020 else False )
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
176,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,Digestive diseases,Rate,2013,2697.039450,2834.479777,2582.161628,Deaths,85.838243,88.899467,82.905470,True
177,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Digestive diseases,Rate,2013,1688.287627,1864.552118,1540.753908,Deaths,54.320030,56.658301,51.582158,True
178,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Digestive diseases,Rate,2013,2179.809770,2326.710260,2053.355455,Deaths,69.677523,72.085742,67.023604,True
526,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,62.211141,67.330638,57.963919,Deaths,0.980503,1.028893,0.938133,True
527,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,48.638280,63.003805,39.937237,Deaths,0.490602,0.521284,0.461069,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Substance use disorders,Rate,2019,295.064646,389.845097,216.597062,Deaths,1.425430,1.754495,1.139157,True
93742,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Substance use disorders,Rate,2019,418.790624,531.482484,325.675656,Deaths,3.606607,4.409484,2.918962,True
93911,DALYs (Disability-Adjusted Life Years),Poland,Male,All Ages,Neglected tropical diseases and malaria,Rate,2019,56.462532,87.853853,34.154091,Deaths,0.026689,0.042530,0.016396,True
93912,DALYs (Disability-Adjusted Life Years),Poland,Female,All Ages,Neglected tropical diseases and malaria,Rate,2019,62.473695,91.811053,38.948680,Deaths,0.019770,0.032317,0.012205,True
93913,DALYs (Disability-Adjusted Life Years),Poland,Both,All Ages,Neglected tropical diseases and malaria,Rate,2019,59.563301,89.349730,36.535688,Deaths,0.023120,0.035061,0.016445,True

In [23]:
# można napisać krócej bez pełnego zapisania tego warunku
df_all['CIS_2020'] = df_all['location'].apply(lambda x: x in CIS_2020)

In [24]:
# wybierz wierszy, które pasują do nowego warunku i sprawdź, czy zostały pomyślnie dodane
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
176,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,Digestive diseases,Rate,2013,2697.039450,2834.479777,2582.161628,Deaths,85.838243,88.899467,82.905470,True
177,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Digestive diseases,Rate,2013,1688.287627,1864.552118,1540.753908,Deaths,54.320030,56.658301,51.582158,True
178,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Digestive diseases,Rate,2013,2179.809770,2326.710260,2053.355455,Deaths,69.677523,72.085742,67.023604,True
526,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,62.211141,67.330638,57.963919,Deaths,0.980503,1.028893,0.938133,True
527,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,48.638280,63.003805,39.937237,Deaths,0.490602,0.521284,0.461069,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Substance use disorders,Rate,2019,295.064646,389.845097,216.597062,Deaths,1.425430,1.754495,1.139157,True
93742,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Substance use disorders,Rate,2019,418.790624,531.482484,325.675656,Deaths,3.606607,4.409484,2.918962,True
93911,DALYs (Disability-Adjusted Life Years),Poland,Male,All Ages,Neglected tropical diseases and malaria,Rate,2019,56.462532,87.853853,34.154091,Deaths,0.026689,0.042530,0.016396,True
93912,DALYs (Disability-Adjusted Life Years),Poland,Female,All Ages,Neglected tropical diseases and malaria,Rate,2019,62.473695,91.811053,38.948680,Deaths,0.019770,0.032317,0.012205,True
93913,DALYs (Disability-Adjusted Life Years),Poland,Both,All Ages,Neglected tropical diseases and malaria,Rate,2019,59.563301,89.349730,36.535688,Deaths,0.023120,0.035061,0.016445,True

In [25]:
# w ten sam sposób możesz zapisać dowolny złożony warunek w osobnej funkcji, a następnie zastosować go do żądanej kolumny
def if_cis(x):
    if x in CIS_2020:
        return True
    else:
        False

In [26]:
df_all['CIS_2020'] = df_all['location'].apply(if_cis)

In [27]:
df_all[df_all['CIS_2020'] == True]

,measure_x,location,sex,age,cause,metric,year,daly_val,daly_upper,daly_lower,measure_y,deaths_val,deaths_upper,deaths_lower,CIS_2020
176,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,Digestive diseases,Rate,2013,2697.039450,2834.479777,2582.161628,Deaths,85.838243,88.899467,82.905470,True
177,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Digestive diseases,Rate,2013,1688.287627,1864.552118,1540.753908,Deaths,54.320030,56.658301,51.582158,True
178,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Digestive diseases,Rate,2013,2179.809770,2326.710260,2053.355455,Deaths,69.677523,72.085742,67.023604,True
526,DALYs (Disability-Adjusted Life Years),Romania,Male,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,62.211141,67.330638,57.963919,Deaths,0.980503,1.028893,0.938133,True
527,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,HIV/AIDS and sexually transmitted infections,Rate,2012,48.638280,63.003805,39.937237,Deaths,0.490602,0.521284,0.461069,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93741,DALYs (Disability-Adjusted Life Years),Romania,Female,All Ages,Substance use disorders,Rate,2019,295.064646,389.845097,216.597062,Deaths,1.425430,1.754495,1.139157,True
93742,DALYs (Disability-Adjusted Life Years),Romania,Both,All Ages,Substance use disorders,Rate,2019,418.790624,531.482484,325.675656,Deaths,3.606607,4.409484,2.918962,True
93911,DALYs (Disability-Adjusted Life Years),Poland,Male,All Ages,Neglected tropical diseases and malaria,Rate,2019,56.462532,87.853853,34.154091,Deaths,0.026689,0.042530,0.016396,True
93912,DALYs (Disability-Adjusted Life Years),Poland,Female,All Ages,Neglected tropical diseases and malaria,Rate,2019,62.473695,91.811053,38.948680,Deaths,0.019770,0.032317,0.012205,True
93913,DALYs (Disability-Adjusted Life Years),Poland,Both,All Ages,Neglected tropical diseases and malaria,Rate,2019,59.563301,89.349730,36.535688,Deaths,0.023120,0.035061,0.016445,True

In [28]:
# zapisz ramkę danych do csv
df_all.to_csv('df_all.csv')

### 4. Praca z dużymi plikami przy użyciu argumentu chunksize

In [29]:
# podziel duży plik na części za pomocą argumentu chunksize, który określa, ile wierszy powinno znajdować się w każdej części
# wydrukuj 5 wierszy każdej wynikowej części

for chunk_df in pd.read_csv('df_all.csv', 
                      chunksize = 50000):
    print("CHUNK DF")
    print(chunk_df.head())

CHUNK DF
   Unnamed: 0                               measure_x location     sex  \
0           0  DALYs (Disability-Adjusted Life Years)   Gambia  Female
1           1  DALYs (Disability-Adjusted Life Years)   Gambia    Both
2           2  DALYs (Disability-Adjusted Life Years)   Gambia    Male
3           3  DALYs (Disability-Adjusted Life Years)   Gambia  Female
4           4  DALYs (Disability-Adjusted Life Years)   Gambia    Both

        age                            cause metric  year     daly_val  \
0  All Ages  Maternal and neonatal disorders   Rate  2012  7475.212700
1  All Ages  Maternal and neonatal disorders   Rate  2012  7814.344518
2  All Ages          Substance use disorders   Rate  2012   179.493660
3  All Ages          Substance use disorders   Rate  2012    91.400543
4  All Ages          Substance use disorders   Rate  2012   134.688036

    daly_upper   daly_lower measure_y  deaths_val  deaths_upper  deaths_lower  \
0  9104.773541  6157.428603    Deaths   89.867238    110.176286     74.001324
1  9667.960848  6289.146375    Deaths   89.365457    111.497307     71.539316
2   230.104586   134.067784    Deaths    1.101136      1.545407      0.786638
3   124.025911    64.625204    Deaths    0.227136      0.296917      0.173921
4   171.782808    99.320179    Deaths    0.656605      0.896138      0.490594

  CIS_2020
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
CHUNK DF
       Unnamed: 0                               measure_x location     sex  \
50000       50000  DALYs (Disability-Adjusted Life Years)    India    Both
50001       50001  DALYs (Disability-Adjusted Life Years)    India    Male
50002       50002  DALYs (Disability-Adjusted Life Years)    India  Female
50003       50003  DALYs (Disability-Adjusted Life Years)    India    Both
50004       50004  DALYs (Disability-Adjusted Life Years)   Turkey    Male

            age                            cause metric  year     daly_val  \
50000  All Ages        Other infectious diseases   Rate  2016   958.958618
50001  All Ages  Maternal and neonatal disorders   Rate  2016  3857.092523
50002  All Ages  Maternal and neonatal disorders   Rate  2016  3936.244203
50003  All Ages  Maternal and neonatal disorders   Rate  2016  3895.617080
50004  All Ages               Transport injuries   Rate  2016   906.078397

        daly_upper   daly_lower measure_y  deaths_val  deaths_upper  \
50000  1253.212194   758.548648    Deaths   14.064804     17.711690
50001  4559.365099  3248.746140    Deaths   39.804065     47.428130
50002  4575.786077  3357.759508    Deaths   42.591026     49.826017
50003  4578.291899  3318.975051    Deaths   41.160530     48.311924
50004  1044.082153   685.161081    Deaths   16.515202     19.376146

       deaths_lower CIS_2020
50000     11.444635      NaN
50001     33.085022      NaN
50002     36.112185      NaN
50003     34.780916      NaN
50004     11.913822      NaN

In [30]:
# zastosuj metodę groupby oddzielnie do każdej części, a następnie połącz wynik w nową ramkę danych
new_df = pd.DataFrame() # pusta ramka danych
for chunk_df in pd.read_csv('df_all.csv', 
                      chunksize = 50000):
    result = chunk_df.groupby(['cause', 'year']).agg({'deaths_val': 'mean',
                                                    'daly_val': 'mean'})
    new_df = pd.concat([new_df,result])

In [31]:
new_df

                              deaths_val     daly_val
cause                   year
Cardiovascular diseases 2011  112.889873  2945.949359
                        2012  238.128059  5118.690134
                        2013  236.486609  5005.051157
                        2014  242.057921  5088.816632
                        2015  253.292782  5250.955897
...                                  ...          ...
Unintentional injuries  2015   24.622137  1575.325187
                        2016   21.095357  1389.698018
                        2017   22.527506  1467.601676
                        2018   21.578766  1428.203221
                        2019   21.508796  1417.611000

[236 rows x 2 columns]

In [32]:
# zapisz wynik do pliku
new_df.to_csv('deaths_daly_groupby.csv', encoding = 'utf-8')

#### Oto koniec