In [1]:
# Zadania:
# • ladowanie biblioteki Pandas
import pandas as pd

# • tworzenie ramki danych ze slownika
a_dict={"asd":[1],
     "dsa": [2]}
ad= pd.DataFrame(a_dict)
ad

   asd  dsa
0    1    2

In [2]:
# • zachowanie ramki danych pobranych z pliku w formacie csv (xlsx)
path=r"C:\Users\USER098\Documents\GitHub\Lessons_About_Data\Data\IHME_PREM_WMN_HEALTH_2020_CODEBOOK_Y2021M10D11.csv"
df = pd.read_csv(path,encoding="utf-8")

df.head()

,variable_name,question,question_type,value,answer_label
0,user_id,User ID,IHME generated,NaN,NaN
1,country,Country name,Text,NaN,NaN
2,observation_id,Observation ID,IHME generated,NaN,NaN
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN
4,gender,What is your gender?,Select one,2.0,Female

In [21]:
# • tworzenie ramki danych z listy list
lista=[["asd","asdf"],
     [1,2]]

pd.DataFrame(lista)

     0     1
0  asd  asdf
1    1     2

In [20]:
# • transponowanie (wymieniamy kolumny a wierszy)
pd.DataFrame(lista).T

      0  1
0   asd  1
1  asdf  2

In [22]:
# • wy´swietli´c pierwsze 10 wierszy ramki danych

df.head(10)

,variable_name,question,question_type,value,answer_label
0,user_id,User ID,IHME generated,NaN,NaN
1,country,Country name,Text,NaN,NaN
2,observation_id,Observation ID,IHME generated,NaN,NaN
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN
4,gender,What is your gender?,Select one,2.0,Female
5,gender,What is your gender?,Select one,1.0,Male
6,gender,What is your gender?,Select one,88.0,Prefer not to respond
7,gender,What is your gender?,Select one,99.0,Not available
8,age,What is your age?,Select one,1.0,Under 16
9,age,What is your age?,Select one,2.0,16 to 25 years old

In [24]:
# • wy´swietli´c ostatnie 10 wierszy ramki danych

df.tail(10)

,variable_name,question,question_type,value,answer_label
211,wmn_no_help_why,What was the main reason you were unable to se...,Select one,1.0,Did not know where to go
212,wmn_no_help_why,What was the main reason you were unable to se...,Select one,2.0,Too far from services
213,wmn_no_help_why,What was the main reason you were unable to se...,Select one,3.0,Could not afford transport or service fees
214,wmn_no_help_why,What was the main reason you were unable to se...,Select one,4.0,Services unavailable due to COVID-19 restrictions
215,wmn_no_help_why,What was the main reason you were unable to se...,Select one,5.0,Unable to travel due to COVID-19 restrictions
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer

In [25]:
# • wy´swietli´c informacje˛ o ramce danych

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   variable_name  221 non-null    str
 1   question       221 non-null    str
 2   question_type  221 non-null    str
 3   value          207 non-null    float64
 4   answer_label   207 non-null    str
dtypes: float64(1), str(4)
memory usage: 8.8 KB

In [27]:
# • wy´swietli´c, ile wierszy i kolumn znajduje sie˛ w ramce danych

df.shape

(221, 5)

In [28]:
# • wy´swietli´c informacje˛ statystyczna˛ o kolumnach liczbowych (warto´sci 
# niepowtarzalne, ´srednia, odchylenie standardowe, minimum, kwartyle, 
# maksimum)

df.describe()

            value
count  207.000000
mean    20.608696
std     33.939932
min      0.000000
25%      2.000000
50%      4.000000
75%     10.500000
max     99.000000

In [4]:
# • wy´swietli´c informacje˛ statystyczna˛ o kolumnach kategoryzowanych (ile 
# unikalnych warto´sci, top - jaka jest najpopularniejsza warto´s´c, freq -
# jak cze˛sto najpopularniejsza)

df.describe(include="all")

,variable_name,question,question_type,value,answer_label
count,221,221,221,207.000000,207
unique,46,46,5,NaN,112
top,wmn_hh,"On average, in the last six months, how many m...",Select one,NaN,Decline to respond
freq,20,20,175,NaN,15
mean,NaN,NaN,NaN,20.608696,NaN
std,NaN,NaN,NaN,33.939932,NaN
min,NaN,NaN,NaN,0.000000,NaN
25%,NaN,NaN,NaN,2.000000,NaN
50%,NaN,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,10.500000,NaN
max,NaN,NaN,NaN,99.000000,NaN

In [11]:
# • usuna˛´c brakuja˛ce warto´sci w ramce danych

df.dropna(inplace=True)

In [10]:
# •przedstawi´c wyb´or wierszy i kolumny u˙ zywaja˛c nazw oraz indeks´ow nar´o˙zne sposoby

df["value"]
df.value
df[["value","answer_label"]]

     value                                       answer_label
4      2.0                                             Female
5      1.0                                               Male
6     88.0                              Prefer not to respond
7     99.0                                      Not available
8      1.0                                           Under 16
..     ...                                                ...
216    6.0  Fear of threats/consequences/getting into trouble
217    7.0                Embarrassed for myself or my family
218   77.0                                         Don't know
219   99.0                                              Other
220   88.0                                  Decline to answer

[207 rows x 2 columns]

In [15]:
# przedstawi´c wyb´ or wierszy z ramki danych pod warunkiem odno´snie 
# okre´slonej warto´sci kolumny

df.loc[:, "question":"value"]
df.loc[200:210, "question":"value"]
df.iloc[100:110, 0:1]

              variable_name
107    wmn_pre_con_accessed
108    wmn_pre_con_accessed
109    wmn_pre_con_accessed
110    wmn_pre_con_accessed
111    wmn_pre_con_accessed
114  wmn_pre_con_missed_why
115  wmn_pre_con_missed_why
116  wmn_pre_con_missed_why
117  wmn_pre_con_missed_why
118  wmn_pre_con_missed_why

In [18]:
# or wierszy z ramki danych pod warunkiem odno´snie 
# okre´slonej warto´sci kolumny

df[df["variable_name"]=="wmn_pre_con_missed_why"]

,variable_name,question,question_type,value,answer_label
114,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,1.0,Health facility closed
115,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,2.0,Turned away from health facility
116,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,3.0,Contraception not available
117,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,4.0,No transportation
118,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,5.0,Lack of money
119,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,8.0,Partner or family does not approve
120,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,99.0,Other
121,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,88.0,Decline to respond

In [3]:
# wybra´c wiersze kt´
# ore zawieraja˛ w kolumnie kategoryzowanej okre´slone
# slowo

df[(df["question"]=="What is your gender")  & (df["value"]==2.0) & (df["answer_label"]=="Male")]

Empty DataFrame
Columns: [variable_name, question, question_type, value, answer_label]
Index: []

In [6]:
# • wybra´c wiersze kt´ore nie zawieraja˛ w kolumnie kategoryzowanej okre´slone
# slowo

df[(~df["question"].str.contains("What is your gender"))  & (df["value"]==2.0) & (~df["answer_label"].str.contains("Male"))]

,variable_name,question,question_type,value,answer_label
9,age,What is your age?,Select one,2.0,16 to 25 years old
15,geography,Where do you live?,Select one,2.0,Suburban/Peri-urban
19,financial_situation,What is your current financial situation?,Select one,2.0,"I can afford food and regular expenses, but no..."
25,education,What is the highest level of schooling you hav...,Select one,2.0,Primary school
33,employment_status,What is your current employment status?,Select one,2.0,Employed part-time
43,wmn_hh,"On average, in the last six months, how many m...",Select one,2.0,2
63,wmn_pregnancy_desire,How long would you like to wait from now befor...,Select one,2.0,I want to have a/another child later
71,wmn_pregnancy_change_how,How has your desire for children changed since...,Select one,2.0,I am now undecided
94,wmn_pre_con_access_difficulty,"During December-February, did you experience a...",Select one,2.0,Did not need contraception
98,wmn_pre_con_needed,"On average during a week, how many times did y...",Select one,2.0,2
106,wmn_pre_con_accessed,How many times were you able to access contrac...,Select one,2.0,2
115,wmn_pre_con_missed_why,What were the reason(s) you were not able to a...,Select multiple,2.0,Turned away from health facility
125,wmn_post_con_access_difficulty,"Since March, did you experience any difficulti...",Select one,2.0,Did not need contraception
129,wmn_post_con_needed,"On average during a week, how many times did y...",Select one,2.0,2
137,wmn_post_con_accessed,How many times during the average week were yo...,Select one,2.0,2
146,wmn_post_con_missed_why,What were the reason(s) you could not access y...,Select multiple,2.0,Turned away from health facility
161,wmn_how_safe,"How safe do you feel in your home, where you c...",Select one,2.0,A little unsafe
167,wmn_safe_change,"Since March, have you felt more or less safe i...",Select one,2.0,About the same
176,wmn_pre_safe_place,"During December-February, how often did you ne...",Select one,2.0,Once a month
183,wmn_post_safe_place,"Since March, how often did you need to go to t...",Select one,2.0,Once a month
193,wmn_safe_place_no_access_why,What was the main reason that prevented you fr...,Select one,2.0,Place was closed or unavailable for reason oth...
212,wmn_no_help_why,What was the main reason you were unable to se...,Select one,2.0,Too far from services

In [9]:
# utworz kolumne˛ na podstawie istnieja˛cych

df["new"]=pd.DataFrame(df['question'])
df

,variable_name,question,question_type,value,answer_label,new
0,user_id,User ID,IHME generated,NaN,NaN,User ID
1,country,Country name,Text,NaN,NaN,Country name
2,observation_id,Observation ID,IHME generated,NaN,NaN,Observation ID
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN,Date and time survey was submitted
4,gender,What is your gender?,Select one,2.0,Female,What is your gender?
...,...,...,...,...,...,...
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble,What was the main reason you were unable to se...
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family,What was the main reason you were unable to se...
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know,What was the main reason you were unable to se...
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other,What was the main reason you were unable to se...
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer,What was the main reason you were unable to se...

In [11]:
# zmien´ nazwe˛ kolumny

df.rename(columns={"new": "new2"}, inplace=True)
df

,variable_name,question,question_type,value,answer_label,new2
0,user_id,User ID,IHME generated,NaN,NaN,User ID
1,country,Country name,Text,NaN,NaN,Country name
2,observation_id,Observation ID,IHME generated,NaN,NaN,Observation ID
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN,Date and time survey was submitted
4,gender,What is your gender?,Select one,2.0,Female,What is your gender?
...,...,...,...,...,...,...
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble,What was the main reason you were unable to se...
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family,What was the main reason you were unable to se...
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know,What was the main reason you were unable to se...
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other,What was the main reason you were unable to se...
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer,What was the main reason you were unable to se...

In [14]:
# zachowaj ramke˛ danych jako plik csv na komputerze

path2=r"C:\Users\USER098\Documents\GitHub\Lessons_About_Data\Data\new2.csv"

df['new2'].to_csv(path2)
df2=pd.read_csv(path2)
df2.head()

   Unnamed: 0                                new2
0           0                             User ID
1           1                        Country name
2           2                      Observation ID
3           3  Date and time survey was submitted
4           4                What is your gender?

In [25]:
# wy´swietli´c ´srednia (maksymalna˛, minimalna˛) warto´s´c z jednej kolumny

df["value_max"] = df["value"].max()
df["value_min"] = df["value"].min()
df["value_mean"] = df["value"].mean()

df[["value_max","value_min","value_mean"]]

     value_max  value_min  value_mean
0         99.0        0.0   20.608696
1         99.0        0.0   20.608696
2         99.0        0.0   20.608696
3         99.0        0.0   20.608696
4         99.0        0.0   20.608696
..         ...        ...         ...
216       99.0        0.0   20.608696
217       99.0        0.0   20.608696
218       99.0        0.0   20.608696
219       99.0        0.0   20.608696
220       99.0        0.0   20.608696

[221 rows x 3 columns]

In [18]:
# wy´swietli´c liczbe˛ wierszy

df.shape

(221, 6)

In [21]:
# wy´swietli´c warto´sci unikatowe w kolumnie

df["question"].unique()

<StringArray>
[                                                                                                                            'User ID',
                                                                                                                        'Country name',
                                                                                                                      'Observation ID',
                                                                                                  'Date and time survey was submitted',
                                                                                                                'What is your gender?',
                                                                                                                   'What is your age?',
                                                                                                                  'Where do you live?',
                                                                                           'What is your current financial situation?',
                                                                          'What is the highest level of schooling you have completed?',
                                                                                             'What is your current employment status?',
                                                                                                             'What is your ethnicity?',
                                                                                                              'What is your religion?',
                              'On average, in the last six months, how many members usually live in your household counting yourself?',
                                                       'How long would you like to wait from now before the birth of a/another child?',
                                                                                  'Since March, has your desire for children changed?',
                                                                               'How has your desire for children changed since March?',
                    'In the last 6 months, have you or your partner used any contraception method to delay or avoid getting pregnant?',
                                   'Indicate which type of contraception method you or your partner have used in the last six months.',
                            'During December-February, did you experience any difficulties in accessing your method of contraception?',
                                                   'On average during a week, how many pills did you miss during December - February?',
                                  'On average during a week, how many times did you require contraception during December - February?',
                              'How many times were you able to access contraception during the average week from December - February?',
 'How many times during December-February did you need either an appointment for an injectable contraception but could not access it?',
                                'How many times during December-February did you need an appointment for IUD but could not access it?',
                          'What were the reason(s) you were not able to access your method of contraception during December-February?',
                                      'Specify the other reason you were not able to access contraception during December - February.',
                                         'Since March, did you experience any difficulties in accessing your method of contraception?',
                                                                  'On average during a week, how many pills did you miss since March?',
                                                 'On average during a week, how many times did you require contraception since March?',
                                           'How many times during the average week were you able to access contraception since March?',
                        'How many times since March did you need an appointment for injectable contraception but could not access it?',
                                          'How many times since March did you need an appointment for an IUD but could not access it?',
                                              'What were the reason(s) you could not access your method of contraception since March?',
                                                     'Specify the other reason you were not able to access contraception since March.',
                                                                                                            'Are you alone right now?',
                                                                       'How safe do you feel in your home, where you currently sleep?',
                                                                          'Since March, have you felt more or less safe in your home?',
                                    'Is there a place that you could go if something happened that made you feel unsafe in your home?',
                                                               'During December-February, how often did you need to go to this place?',
                                                                            'Since March, how often did you need to go to this place?',
                                              'Since March, did you intend to go to this safe place but were prevented from doing so?',
                                                               'What was the main reason that prevented you from going to this place?',
       'During December-February, have you sought the services of a women's help organization (e.g. crisis center, shelter, hotline)?',
                    'Since March, have you sought the services of a women's help organization (e.g. crisis center, shelter, hotline)?',
                                       'Since March, have you wanted to seek the services of a women's help organization but did not?',
                                       'What was the main reason you were unable to seek the services of a women's help organization?']
Length: 46, dtype: str

In [27]:
# wy´swietli´c liczby rekord´ow odpowiadaja˛cych do warto´sci

df["question"].value_counts()

question
On average, in the last six months, how many members usually live in your household counting yourself?                                 20
Indicate which type of contraception method you or your partner have used in the last six months.                                      14
What were the reason(s) you could not access your method of contraception since March?                                                 10
What was the main reason you were unable to seek the services of a women's help organization?                                          10
What is the highest level of schooling you have completed?                                                                              8
What is your current employment status?                                                                                                 8
On average during a week, how many times did you require contraception during December - February?                                      8
How many times were you able to access contraception during the average week from December - February?                                  8
What were the reason(s) you were not able to access your method of contraception during December-February?                              8
On average during a week, how many times did you require contraception since March?                                                     8
How many times during the average week were you able to access contraception since March?                                               8
During December-February, how often did you need to go to this place?                                                                   7
Since March, how often did you need to go to this place?                                                                                7
What was the main reason that prevented you from going to this place?                                                                   7
What is your age?                                                                                                                       6
What is your current financial situation?                                                                                               6
How long would you like to wait from now before the birth of a/another child?                                                           6
How has your desire for children changed since March?                                                                                   6
How safe do you feel in your home, where you currently sleep?                                                                           6
Since March, have you felt more or less safe in your home?                                                                              5
What is your gender?                                                                                                                    4
Where do you live?                                                                                                                      4
Is there a place that you could go if something happened that made you feel unsafe in your home?                                        4
Since March, did you intend to go to this safe place but were prevented from doing so?                                                  4
During December-February, have you sought the services of a women's help organization (e.g. crisis center, shelter, hotline)?           4
Since March, have you sought the services of a women's help organization (e.g. crisis center, shelter, hotline)?                        4
Since March, have you wanted to seek the services of a women's help organization but did not?                                           4
During December-February, did you experience any difficulties in accessing your method of contraception?                                3
Since March, did you experience any difficulties in accessing your method of contraception?                                             3
Are you alone right now?                                                                                                                3
Since March, has your desire for children changed?                                                                                      2
In the last 6 months, have you or your partner used any contraception method to delay or avoid getting pregnant?                        2
User ID                                                                                                                                 1
Country name                                                                                                                            1
Observation ID                                                                                                                          1
Date and time survey was submitted                                                                                                      1
What is your ethnicity?                                                                                                                 1
What is your religion?                                                                                                                  1
On average during a week, how many pills did you miss during December - February?                                                       1
How many times during December-February did you need either an appointment for an injectable contraception but could not access it?     1
How many times during December-February did you need an appointment for IUD but could not access it?                                    1
Specify the other reason you were not able to access contraception during December - February.                                          1
On average during a week, how many pills did you miss since March?                                                                      1
How many times since March did you need an appointment for injectable contraception but could not access it?                            1
How many times since March did you need an appointment for an IUD but could not access it?                                              1
Specify the other reason you were not able to access contraception since March.                                                         1
Name: count, dtype: int64

In [34]:
# sortowanie wierszy ramki danych wedlug warto´sci okre´slonej kolumny
# (maleja˛co, rosna˛co)

# df.sort_values(['value'],ascending=False)
df["value1"] = df["value"].sort_values(ascending=False).values
df["value2"] = df["value"].sort_values(ascending=True).values
df[["value1","value1"]]

     value1  value1
0      99.0    99.0
1      99.0    99.0
2      99.0    99.0
3      99.0    99.0
4      99.0    99.0
..      ...     ...
216     NaN     NaN
217     NaN     NaN
218     NaN     NaN
219     NaN     NaN
220     NaN     NaN

[221 rows x 2 columns]

In [42]:
# wy´swietli´c wierszy dla 10 najwie˛kszych (najmniejszych) warto´sci okre´slonej
# kolumny


df.nlargest(10,'value')
df.nsmallest(10,'value')

,variable_name,question,question_type,value,answer_label,new2,value_max,value_min,value_mean,value1,value2
69,wmn_pregnancy_change,"Since March, has your desire for children chan...",Select one,0.0,No,"Since March, has your desire for children chan...",99.0,0.0,20.608696,6.0,2.0
77,wmn_con,"In the last 6 months, have you or your partner...",Select one,0.0,No,"In the last 6 months, have you or your partner...",99.0,0.0,20.608696,6.0,3.0
93,wmn_pre_con_access_difficulty,"During December-February, did you experience a...",Select one,0.0,No,"During December-February, did you experience a...",99.0,0.0,20.608696,5.0,4.0
96,wmn_pre_con_needed,"On average during a week, how many times did y...",Select one,0.0,0,"On average during a week, how many times did y...",99.0,0.0,20.608696,4.0,4.0
104,wmn_pre_con_accessed,How many times were you able to access contrac...,Select one,0.0,0,How many times were you able to access contrac...,99.0,0.0,20.608696,4.0,4.0
124,wmn_post_con_access_difficulty,"Since March, did you experience any difficulti...",Select one,0.0,No,"Since March, did you experience any difficulti...",99.0,0.0,20.608696,3.0,5.0
127,wmn_post_con_needed,"On average during a week, how many times did y...",Select one,0.0,0,"On average during a week, how many times did y...",99.0,0.0,20.608696,3.0,5.0
135,wmn_post_con_accessed,How many times during the average week were yo...,Select one,0.0,0,How many times during the average week were yo...,99.0,0.0,20.608696,2.0,6.0
157,wmn_alone,Are you alone right now?,Select one,0.0,No,Are you alone right now?,99.0,0.0,20.608696,2.0,12.0
171,wmn_safe_place,Is there a place that you could go if somethin...,Select one,0.0,No,Is there a place that you could go if somethin...,99.0,0.0,20.608696,1.0,77.0

In [23]:





# • wy´swietli´c wierszy dla 10 najwie˛kszych (najmniejszych) warto´sci okre´slonej
# kolumny

# • wy´swietli´c wierszy dla 10 najwie˛kszych warto´sci okre´slonej kolumny
# pod warunkiem okre´slonych warto´sci innej kolumny

# • grupowanie wierszy wedlug warto´sci kolumny kategoryzowanej, potem
# - u´srednienie warto´sci wszystkich kolumn w grupie - MultiIndex

# • grupowanie wierszy wedlug warto´sci kolumny kategoryzowanej, potem 
# - u´srednienie warto´sci dla pewnych kolumn, liczba warto´sci i mediana 
# dla pozostalych kolumn w grupach

# • wy´swietli´c nazwy kolumn indeksu zlo˙

# zonego

# • sortowa´c kolumne˛ indeksu zlo˙

# zonego

# • stworzy´c tabele˛ przystawna˛ (pivot table) na podstawie ramki danych

# • wy´swietli´c indeksy i kolumny tabeli przystawnej

# • utw´

# orz indeks zlo˙

# zony tabeli przystawnej i wy´swietl go

# • zaimportuj modul pyplot z biblioteki matplotlib

# 7


# • wskaza´c, ˙

# ze wykresy nale˙

# zy rysowa´c bezpo´srednio w zeszycie, a nie w

# osobnej zakladce

# • wy´swietli´c wykres na podstawie tabeli przystawnej

# • narysowa´c histogram na podstawie warto´sci kolumny

# • przedstawi´c sposoby la˛czenia ramek danych za pomoca˛ metod merge i
# concat

# • pokaza´c dodawanie nowych kolumn za pomoca˛ operacji matematy-
# cznych

# • przedstawi´c na przykladzie dodawanie nowych kolumn z pomoca˛ funkcji
# lambda

# • przedstawi´c mo˙

# zliwo´sci pracy z du˙

# zymi plikami przy u˙

# zyciu argumentu

# chunksize

,variable_name,question,question_type,value,answer_label
211,wmn_no_help_why,What was the main reason you were unable to se...,Select one,1.0,Did not know where to go
212,wmn_no_help_why,What was the main reason you were unable to se...,Select one,2.0,Too far from services
213,wmn_no_help_why,What was the main reason you were unable to se...,Select one,3.0,Could not afford transport or service fees
214,wmn_no_help_why,What was the main reason you were unable to se...,Select one,4.0,Services unavailable due to COVID-19 restrictions
215,wmn_no_help_why,What was the main reason you were unable to se...,Select one,5.0,Unable to travel due to COVID-19 restrictions
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer