In [14]:
# Zadania:
# • ladowanie biblioteki Pandas
import pandas as pd

# • tworzenie ramki danych ze slownika
a_dict={"asd":[1],
     "dsa": [2]}
ad= pd.DataFrame(a_dict)
ad

   asd  dsa
0    1    2

In [15]:
# • zachowanie ramki danych pobranych z pliku w formacie csv (xlsx)
path=r"C:\Users\USER098\Documents\GitHub\Lessons_About_Data\Data\IHME_PREM_WMN_HEALTH_2020_CODEBOOK_Y2021M10D11.csv"
df = pd.read_csv(path,encoding="utf-8")

df.head()

,variable_name,question,question_type,value,answer_label
0,user_id,User ID,IHME generated,NaN,NaN
1,country,Country name,Text,NaN,NaN
2,observation_id,Observation ID,IHME generated,NaN,NaN
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN
4,gender,What is your gender?,Select one,2.0,Female

In [21]:
# • tworzenie ramki danych z listy list
lista=[["asd","asdf"],
     [1,2]]

pd.DataFrame(lista)

     0     1
0  asd  asdf
1    1     2

In [20]:
# • transponowanie (wymieniamy kolumny a wierszy)
pd.DataFrame(lista).T

      0  1
0   asd  1
1  asdf  2

In [22]:
# • wy´swietli´c pierwsze 10 wierszy ramki danych

df.head(10)

,variable_name,question,question_type,value,answer_label
0,user_id,User ID,IHME generated,NaN,NaN
1,country,Country name,Text,NaN,NaN
2,observation_id,Observation ID,IHME generated,NaN,NaN
3,submitted_time,Date and time survey was submitted,Built-in data,NaN,NaN
4,gender,What is your gender?,Select one,2.0,Female
5,gender,What is your gender?,Select one,1.0,Male
6,gender,What is your gender?,Select one,88.0,Prefer not to respond
7,gender,What is your gender?,Select one,99.0,Not available
8,age,What is your age?,Select one,1.0,Under 16
9,age,What is your age?,Select one,2.0,16 to 25 years old

In [24]:
# • wy´swietli´c ostatnie 10 wierszy ramki danych

df.tail(10)

,variable_name,question,question_type,value,answer_label
211,wmn_no_help_why,What was the main reason you were unable to se...,Select one,1.0,Did not know where to go
212,wmn_no_help_why,What was the main reason you were unable to se...,Select one,2.0,Too far from services
213,wmn_no_help_why,What was the main reason you were unable to se...,Select one,3.0,Could not afford transport or service fees
214,wmn_no_help_why,What was the main reason you were unable to se...,Select one,4.0,Services unavailable due to COVID-19 restrictions
215,wmn_no_help_why,What was the main reason you were unable to se...,Select one,5.0,Unable to travel due to COVID-19 restrictions
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer

In [25]:
# • wy´swietli´c informacje˛ o ramce danych

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   variable_name  221 non-null    str
 1   question       221 non-null    str
 2   question_type  221 non-null    str
 3   value          207 non-null    float64
 4   answer_label   207 non-null    str
dtypes: float64(1), str(4)
memory usage: 8.8 KB

In [27]:
# • wy´swietli´c, ile wierszy i kolumn znajduje sie˛ w ramce danych

df.shape

(221, 5)

In [28]:
# • wy´swietli´c informacje˛ statystyczna˛ o kolumnach liczbowych (warto´sci 
# niepowtarzalne, ´srednia, odchylenie standardowe, minimum, kwartyle, 
# maksimum)

df.describe()

            value
count  207.000000
mean    20.608696
std     33.939932
min      0.000000
25%      2.000000
50%      4.000000
75%     10.500000
max     99.000000

In [ ]:
# • wy´swietli´c informacje˛ statystyczna˛ o kolumnach kategoryzowanych (ile 
# unikalnych warto´sci, top - jaka jest najpopularniejsza warto´s´c, freq -
# jak cze˛sto najpopularniejsza)

In [23]:





# • wy´swietli´c informacje˛ statystyczna˛ o kolumnach kategoryzowanych (ile 
# unikalnych warto´sci, top - jaka jest najpopularniejsza warto´s´c, freq -
# jak cze˛sto najpopularniejsza)

# • usuna˛´c brakuja˛ce warto´sci w ramce danych

# 5


# • przedstawi´c wyb´or wierszy i kolumny u˙

# zywaja˛c nazw oraz indeks´ow na

# r´o˙

# zne sposoby

# • przedstawi´c wyb´

# or wierszy z ramki danych pod warunkiem odno´snie 
# okre´slonej warto´sci kolumny

# • przedstawi´c wyb´

# or wierszy z ramki danych pod warunkiem spelnienia 
# kilku warunk´ow jednocze´snie

# • wybra´c wiersze kt´

# ore zawieraja˛ w kolumnie kategoryzowanej okre´slone

# slowo

# • wybra´c wiersze kt´ore nie zawieraja˛ w kolumnie kategoryzowanej okre´slone
# slowo

# • utw´

# orz kolumne˛ na podstawie istnieja˛cyn

# • usun´ kolumne˛

# • zmien´ nazwe˛ kolumny

# • zachowaj ramke˛ danych jako plik csv na komputerze

# • wy´swietli´c ´srednia (maksymalna˛, minimalna˛) warto´s´c z jednej kolumny

# • wy´swietli´c liczbe˛ wierszy

# • wy´swietli´c warto´sci unikatowe w kolumnie

# 6


# • wy´swietli´c liczby rekord´ow odpowiadaja˛cych do warto´sci

# • sortowanie wierszy ramki danych wedlug warto´sci okre´slonej kolumny
# (maleja˛co, rosna˛co)

# • wy´swietli´c wierszy dla 10 najwie˛kszych (najmniejszych) warto´sci okre´slonej
# kolumny

# • wy´swietli´c wierszy dla 10 najwie˛kszych warto´sci okre´slonej kolumny
# pod warunkiem okre´slonych warto´sci innej kolumny

# • grupowanie wierszy wedlug warto´sci kolumny kategoryzowanej, potem
# - u´srednienie warto´sci wszystkich kolumn w grupie - MultiIndex

# • grupowanie wierszy wedlug warto´sci kolumny kategoryzowanej, potem 
# - u´srednienie warto´sci dla pewnych kolumn, liczba warto´sci i mediana 
# dla pozostalych kolumn w grupach

# • wy´swietli´c nazwy kolumn indeksu zlo˙

# zonego

# • sortowa´c kolumne˛ indeksu zlo˙

# zonego

# • stworzy´c tabele˛ przystawna˛ (pivot table) na podstawie ramki danych

# • wy´swietli´c indeksy i kolumny tabeli przystawnej

# • utw´

# orz indeks zlo˙

# zony tabeli przystawnej i wy´swietl go

# • zaimportuj modul pyplot z biblioteki matplotlib

# 7


# • wskaza´c, ˙

# ze wykresy nale˙

# zy rysowa´c bezpo´srednio w zeszycie, a nie w

# osobnej zakladce

# • wy´swietli´c wykres na podstawie tabeli przystawnej

# • narysowa´c histogram na podstawie warto´sci kolumny

# • przedstawi´c sposoby la˛czenia ramek danych za pomoca˛ metod merge i
# concat

# • pokaza´c dodawanie nowych kolumn za pomoca˛ operacji matematy-
# cznych

# • przedstawi´c na przykladzie dodawanie nowych kolumn z pomoca˛ funkcji
# lambda

# • przedstawi´c mo˙

# zliwo´sci pracy z du˙

# zymi plikami przy u˙

# zyciu argumentu

# chunksize

,variable_name,question,question_type,value,answer_label
211,wmn_no_help_why,What was the main reason you were unable to se...,Select one,1.0,Did not know where to go
212,wmn_no_help_why,What was the main reason you were unable to se...,Select one,2.0,Too far from services
213,wmn_no_help_why,What was the main reason you were unable to se...,Select one,3.0,Could not afford transport or service fees
214,wmn_no_help_why,What was the main reason you were unable to se...,Select one,4.0,Services unavailable due to COVID-19 restrictions
215,wmn_no_help_why,What was the main reason you were unable to se...,Select one,5.0,Unable to travel due to COVID-19 restrictions
216,wmn_no_help_why,What was the main reason you were unable to se...,Select one,6.0,Fear of threats/consequences/getting into trouble
217,wmn_no_help_why,What was the main reason you were unable to se...,Select one,7.0,Embarrassed for myself or my family
218,wmn_no_help_why,What was the main reason you were unable to se...,Select one,77.0,Don't know
219,wmn_no_help_why,What was the main reason you were unable to se...,Select one,99.0,Other
220,wmn_no_help_why,What was the main reason you were unable to se...,Select one,88.0,Decline to answer